### PR TITLE
test: fixed the flaky test

### LINKED ISSUE #259: vision.it.ITSystemTest: detectWebEntitiesIncludeGeoResultsTest failed
Note: #183 was also for this test, but it was closed more than 10 days ago. So, I didn't mark it flaky.

----

commit: 4e10eb085c96e0cad513e3f4fd2df667dad5976f
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/d0496517-f398-4e47-9aea-e514a77163c0), [Sponge](http://sponge2/d0496517-f398-4e47-9aea-e514a77163c0)
status: failed
<details><summary>Test output</summary><br><pre>expected to contain: Skyscraper
but was            : [Electra Tower, , גולן טלקום משרדי חברה, Suburb, Metropolitan area, , Maccabi Healthcare Services, , High-rise building, Aerial photography]
	at com.google.cloud.vision.it.ITSystemTest.detectWebEntitiesIncludeGeoResultsTest(ITSystemTest.java:503)
</pre></details>

### PR DESCRIPTION
**Pull request by munkhuushmgl**
Fixes #259 ☕️

### CODE REVIEW

File: google-cloud-vision/src/test/java/com/google/cloud/vision/it/ITSystemTest.java [hunk 1]
```diff
@@ -500,7 +500,10 @@ public void detectWebEntitiesIncludeGeoResultsTest() throws IOException {
         actual.add(entity.getDescription());
       }
     }
-    assertThat(actual).contains("Skyscraper");
+    List<String> expectedResults = new ArrayList<>();
+    expectedResults.add("Skyscraper");
+    expectedResults.add("Suburb");
```
Comment (chingor13) [inline google-cloud-vision/src/test/java/com/google/cloud/vision/it/ITSystemTest.java:505]: nit: you could make this a one-liner with Guava's `Lists.newArrayList("string1", "string2")`

**Review by chingor13 — APPROVED** [review]
